spring:
  application:
    name: fbills

  jackson:
    date-format: "yyyy-MM-dd HH:mm:ss"
    default-property-inclusion: non_null
    deserialization:
      fail-on-null-for-primitives: true

  profiles:
    active: ${SCOPE:stage}

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

mail:
  apiKey: ${EMAIL_APIKEY:mock}
  apiSecret: ${EMAIL_APISECRET:mock}

api:
  app:
    jwtCookieName: token
    jwtSecret: ${SECRET:localSecret}
    jwtExpirationMs: 86400000