spring:
  application:
    name: fbills

  jackson:
    date-format: "yyyy-MM-dd HH:mm:ss"
    default-property-inclusion: non_null
    deserialization:
      fail-on-null-for-primitives: true

  profiles:
    active: ${SCOPE:stage}

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:migrations

  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${GIT_CLIENT_ID}
            client-secret: ${GIT_CLIENT_SECRET}
            scope: read:user
            redirect-uri: "{baseUrl}/login/oauth2/code/github"
            client-name: GitHub
        provider:
          github:
            authorization-uri: https://github.com/login/oauth/authorize
            token-uri: https://github.com/login/oauth/access_token
            user-info-uri: https://api.github.com/user
            user-name-attribute: id

api:
  app:
    jwtSecret: ${SECRET:45da2ed9f455817623087c49390b2ab9e4d38421c20f5a282a877f8e6662c67b361a0f7bd810cbca8e471e183c41d9a648b057aed0369b67078c6d73e38d942e}
    jwtExpirationMs: 86400000
