name: Free Bills Pipeline
on:
  push:
    branches:
      - master
    tags:
      - 'v*.*.*'

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'adopt'
          cache: gradle

      - name: Build with Gradle
        run: ./gradlew compileJava

      - name: Build again
        run: ./gradlew assemble

      - name: Bump version and push tag
        id: tagging
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GIT_TOKEN }}

      - name: Create a GitHub release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tagging.outputs.new_tag }}
          name: Release ${{ steps.tagging.outputs.new_tag }}
          body: ${{ steps.tagging.outputs.changelog }}

#      - name: Bump version and push tag
#        uses: anothrNick/github-tag-action@1.64.0
#        env:
#          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
#          WITH_V: true
#          PRERELEASE: true
#          DEFAULT_BUMP: patch

#      - name: Docker meta
#        id: meta
#        uses: docker/metadata-action@v4
#        with:
#          images: warleyvods/freebills-api

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKER_USER}}
          password: ${{secrets.DOCKER_PASSWORD}}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: warleyvods/freebills-api:${{ steps.tagging.outputs.new_version }}
          platforms: linux/amd64,linux/arm64

      - name: Deploy Kubernetes
        uses: steebchen/kubectl@v2.1.1
        with:
          config: ${{ secrets.KUBE_CONFIG }}
          command: set image deployment/freebills-api freebills-api=warleyvods/freebills-api:${{ steps.tagging.outputs.new_version }}

